# Don't edit this file
#
# It was auto generated by cmake from project.json which should be edited instead

set(NAP_MODULES mod_napapp mod_napcameracontrol mod_napparametergui mod_depthaicore mod_depthaicoresemanticsegexample)
