# Don't edit this file
#
# It was auto generated by cmake from module.json which should be edited instead

set(DEPENDENT_NAP_MODULES mod_naprender mod_napscene mod_napparameter)
set(DEEP_DEPENDENT_NAP_MODULES mod_naprender mod_napscene mod_napparameter mod_napfont mod_napinput mod_napcolor mod_napmath)
